name: Format Check

on:
  pull_request:
    paths:
      - 'Controller/**'

jobs:
  ruff_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff format
        run: |
          ruff format Controller

      - name: Commit formatted code
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git diff --cached --exit-code || (git commit -m "Apply ruff formatting" && git push)
